# python compound intrest calculator



principle = 0
rate = 0
time = 0

while principle <= 0:
    principle = float(input("Enter the principle amount: "))
    if principle <= 0:
        print("Principle can't be zero less than or equal to zero")

print("Principle is :" , principle)

while rate <= 0:
    rate = float(input("Enter the interest rate amount: "))
    if rate <= 0:
        print("Interest rate can't be zero less than or equal to zero")

print("Interest rate :" , rate)

while time <= 0:
    time = int(input("Enter the time in years: "))
    if time <= 0:
        print("time can't be zero less than or equal to zero")

print("time :" , time)

total = principle * pow((1 + rate/100) , time)
print(f"Balance after {time} year's : ${total:.2f}")
    
